[package]
name = "ayame"
links = "ayame"
version.workspace = true
edition.workspace = true

[dependencies]
ayame-colors = { path = "../../crates/colors" }
ayame-config = { path = "../../crates/config" }
ayame-icons = { path = "../../crates/icons" }
ayame-stylekit = { path = "../stylekit" }

#[ Crates.io ]
cxx = { workspace = true }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["qt_full"] }

[build-dependencies]
cxx-qt-build = { workspace = true }
