[package]
name = "ayame"
links = "ayame"
version.workspace = true
edition.workspace = true

[dependencies]
ayame-colors = { workspace = true }
ayame-config = { workspace = true }
ayame-icons = { workspace = true }
ayame-stylekit = { workspace = true }

#[ Crates.io ]
cxx = { workspace = true }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["qt_full"] }

[build-dependencies]
cxx-qt-build = { workspace = true }
