[package]
name = "ayame-settings"
version.workspace = true
edition.workspace = true

[dependencies]
ayame = { workspace = true }
ayame-config = { workspace = true }

#[ Crates.io ]
anyhow = { workspace = true }
cxx = { workspace = true }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["qt_full"] }

[build-dependencies]
cxx-qt-build = { workspace = true }
