// Freedesktop-style icon name -> vendored Tabler Icons filename.
//
// Consumers (Ayame's own `Icon.qml`, sibling apps) keep using the
// freedesktop-style names on the left; the Tabler filename on the right
// is where `../vendor/tabler-icons/outline/<name>.svg` actually lives and
// is otherwise an internal implementation detail of this crate. See
// `.agents/tasks/bundle-tabler-icons.md` in the workspace root for how
// each pick was made.
//
// This file is also `include!`d directly by `build.rs` (which cannot
// depend on this crate's own `lib.rs`), so it must stay free of anything
// beyond a plain `pub const` -- no inner doc comments, no imports.

pub const MAPPING: &[(&str, &str)] = &[
    ("accessories-text-editor", "file-text"),
    ("application-menu-symbolic", "menu-2"),
    ("application-pdf", "file-type-pdf"),
    ("arrow-down", "arrow-down"),
    ("arrow-down-symbolic", "arrow-down"),
    ("arrow-left", "arrow-left"),
    ("arrow-left-symbolic", "arrow-left"),
    ("arrow-right", "arrow-right"),
    ("arrow-right-symbolic", "arrow-right"),
    ("audio-volume-high", "volume"),
    ("audio-volume-muted", "volume-off"),
    ("cards-block-symbolic", "layout-cards"),
    ("checkbox", "checkbox"),
    ("chevron-down", "chevron-down"),
    ("chevron-right", "chevron-right"),
    ("code-context", "code"),
    ("code-context-symbolic", "code"),
    ("dialog-error-symbolic", "alert-circle"),
    ("dialog-information-symbolic", "info-circle"),
    ("dialog-warning-symbolic", "alert-triangle"),
    ("document-cleanup", "recycle"),
    ("document-edit-symbolic", "edit"),
    ("document-new", "file-plus"),
    ("document-open-symbolic", "folder-open"),
    ("document-properties", "list-details"),
    ("document-save", "device-floppy"),
    ("document-save-symbolic", "device-floppy"),
    ("draw-brush", "brush"),
    ("edit-delete", "trash"),
    ("edit-find-symbolic", "search"),
    ("emblem-success-symbolic", "circle-check"),
    ("emblem-symbolic-link", "link"),
    ("emblem-warning", "alert-triangle"),
    ("folder", "folder"),
    ("folder-bookmarks", "bookmark"),
    ("folder-documents", "files"),
    ("folder-download", "download"),
    ("folder-music", "music"),
    ("folder-pictures", "photo"),
    ("folder-symbolic", "folder"),
    ("folder-videos", "video"),
    ("globe-symbolic", "world"),
    ("go-down", "chevron-down"),
    ("go-down-symbolic", "chevron-down"),
    ("go-next", "chevron-right"),
    ("go-previous", "chevron-left"),
    ("go-up", "chevron-up"),
    ("go-up-symbolic", "chevron-up"),
    ("im-user", "user"),
    ("image-x-generic", "photo"),
    ("insert-image", "photo"),
    ("internet-web-browser", "world-www"),
    ("list-add-symbolic", "plus"),
    ("list-remove-symbolic", "minus"),
    ("map-flat", "map"),
    ("media-playback-pause", "player-pause"),
    ("media-playback-start", "player-play"),
    ("network-wireless", "wifi"),
    ("network-wireless-disconnected", "wifi-off"),
    ("network-workgroup", "topology-star"),
    ("note-symbolic", "note"),
    ("object-locked", "lock"),
    ("object-unlocked", "lock-open"),
    ("open-menu-symbolic", "menu-2"),
    ("preferences-desktop-theme", "palette"),
    ("preferences-system", "settings"),
    ("preferences-system-symbolic", "settings"),
    ("search", "search"),
    ("sidebar-collapse-left", "layout-sidebar-left-collapse"),
    ("sidebar-expand-left", "layout-sidebar-left-expand"),
    ("sidebar-expand-symbolic", "layout-sidebar"),
    ("tab-duplicate-symbolic", "copy"),
    ("tab-new-symbolic", "plus"),
    ("text-markdown", "markdown"),
    ("text-x-generic", "file-text"),
    ("user-desktop", "device-desktop"),
    ("user-home", "home"),
    ("utilities-terminal", "terminal"),
    ("vcs-branch", "git-branch"),
    ("video-x-generic", "video"),
    ("view-3d", "perspective"),
    ("view-calendar-month", "calendar"),
    ("view-calendar-timeline", "timeline"),
    ("view-filter", "filter"),
    ("view-grid", "layout-grid"),
    ("view-grid-symbolic", "layout-grid"),
    ("view-list-details", "table"),
    ("view-list-icons", "apps"),
    ("view-list-icons-symbolic", "apps"),
    ("view-list-symbolic", "list"),
    ("view-list-tree", "list-tree"),
    ("view-pim-notes", "notes"),
    ("view-preview-symbolic", "eye"),
    ("view-refresh", "refresh"),
    ("view-refresh-symbolic", "refresh"),
    ("view-sort-ascending-symbolic", "sort-ascending"),
    ("view-statistics", "chart-bar"),
    ("view-visible-symbolic", "eye"),
    ("window-close-symbolic", "x"),
];
