[package]
name = "ayame-settings"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
ayame = { path = "../crates/qml6" }
cxx = { workspace = true }
cxx-qt = { workspace = true }
cxx-qt-lib = { workspace = true, features = ["qt_full"] }
directories = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[build-dependencies]
cxx-qt-build = { workspace = true }
